name: Release
on: workflow_dispatch
jobs:
  build-project:
    name: Build Python project
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install PyInstaller
        run: |
          pip install pyinstaller
      - name: Build executable
        run: |
          pyinstaller main.py --onefile -w
      - uses: actions/upload-artifact@v3
        with:
          name: site-build
          path: dist/
